services:
  lingua-translate:
    build: .
    container_name: multilanguage_model-lingua-translate-1
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "5000:5000"

  redis:
    image: redis:7-alpine
    container_name: multilanguage_model-redis-1
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
