# Replace your main.py with the enhanced version (copy from first artifact above)
cp main.py main.py.backup
# Then paste the enhanced main.py content

# Restart the service
docker-compose down && docker-compose up --build -d

# Wait for startup
sleep 30

# Test French translation (should work properly now)
curl -X POST http://localhost:5000/translate -H "Content-Type: application/json" -d '{"text": "Your premium subscription has been activated successfully", "target_lang": "fr"}'