# Optimized Kubernetes Deployment for Lingua Translate
# This version increases the probe timeouts to give the application
# enough time to download and load its large AI models.

apiVersion: v1
kind: Namespace
metadata:
  name: lingua-translate
  labels:
    app: lingua-translate
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lingua-translate-config
  namespace: lingua-translate
data:
  FLASK_ENV: "production"
  PYTHONUNBUFFERED: "1"
  LOG_LEVEL: "INFO"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lingua-translate
  namespace: lingua-translate
  labels:
    app: lingua-translate
    version: v1.0
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: lingua-translate
  template:
    metadata:
      labels:
        app: lingua-translate
        version: v1.0
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: lingua-translate
        image: muhamadabbas/my-lingua-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        envFrom:
        - configMapRef:
            name: lingua-translate-config
        resources:
          requests:
            memory: "2Gi"
            cpu: "200m"
          limits:
            memory: "4Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 120 # Increased initial delay to 120 seconds
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 60  # Increased initial delay to 60 seconds
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: lingua-translate-service
  namespace: lingua-translate
  labels:
    app: lingua-translate
spec:
  type: LoadBalancer
  selector:
    app: lingua-translate
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  sessionAffinity: None
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lingua-translate-hpa
  namespace: lingua-translate
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lingua-translate
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
