# Complete Kubernetes Deployment for Translation Service

# 1. Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: lingua-translate
  labels:
    app: lingua-translate
---

# 2. ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: lingua-translate-config
  namespace: lingua-translate
data:
  FLASK_ENV: "production"
  PYTHONUNBUFFERED: "1"
  LOG_LEVEL: "INFO"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
---

# 3. Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: lingua-translate
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        command: ["redis-server", "--appendonly", "yes"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {}
---

# 4. Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: lingua-translate
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
---

# 5. Translation App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lingua-translate
  namespace: lingua-translate
  labels:
    app: lingua-translate
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lingua-translate
  template:
    metadata:
      labels:
        app: lingua-translate
    spec:
      containers:
      - name: lingua-translate
        image: your-registry/lingua-translate:latest  # Replace with your image
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: lingua-translate-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
---

# 6. Translation Service
apiVersion: v1
kind: Service
metadata:
  name: lingua-translate-service
  namespace: lingua-translate
  labels:
    app: lingua-translate
spec:
  selector:
    app: lingua-translate
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer
---

# 7. Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lingua-translate-hpa
  namespace: lingua-translate
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lingua-translate
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---

# 8. NetworkPolicy for security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lingua-translate-network-policy
  namespace: lingua-translate
spec:
  podSelector:
    matchLabels:
      app: lingua-translate
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx
    ports:
    - protocol: TCP
      port: 5000
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
---

# 9. ServiceMonitor for Prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lingua-translate-metrics
  namespace: lingua-translate
  labels:
    app: lingua-translate
spec:
  selector:
    matchLabels:
      app: lingua-translate
  endpoints:
  - port: http
    path: /metrics
    interval: 30s